### ISSUE TITLE
Code example

### ISSUE THREAD

**Issue by snowch** [synsys/spark#7]
Is there a code example available showing how to use this package?

E.g. something similar to: https://github.com/apache/spark/blob/master/examples/src/main/scala/org/apache/spark/examples/streaming/NetworkWordCount.scala

**Comment by sbrewin** [comment]
The unit tests show how to use this package, particularly https://github.com/synsys/spark/tree/master/spark-streaming-camel_2.10/src/test/java/com/synsys/org/apache/spark/streaming. Though written in Java they are easily translated into Scala if desired.

**Comment by snowch** [comment]
It would be great to see a helloworld scala example on the README.md

**Comment by sbrewin** [comment]
A “helloworld" example in README.md would be less useful than the information that already exists in the project. Certainly README.md should be updated to point to this information; for usage https://github.com/synsys/spark/blob/master/spark-streaming-camel_2.10/src/main/scala/com/synsys/org/apache/spark/streaming/camel/package.scala and for code examples the unit tests https://github.com/synsys/spark/tree/master/spark-streaming-camel_2.10/src/test/java/com/synsys/org/apache/spark/streaming.

We will update the README.md accordingly.

The unit tests are written in Java. Translating these to Scala should not be a stretch for most, but yes, a functional unit test in Scala may be helpful to some. I will create a separate issue for this.
